name: publish_to_pages
on:
  push:
    branches:
      - "main"
      - "jsonld_IV"
      
jobs:
  push2production:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH: ${{ github.ref_name }}
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      statuses: write
    steps:


      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the complete commit history
          
      - name: Set up Git
        run: |
          git config user.email "daniel.ellis@ext.esa.int"
          git config user.name "Daniel Ellis"
          git config credential.helper store
          git config --global user.email "daniel.ellis@ext.esa.int"
          git config --global user.name "Daniel Ellis"
          git config --global push.default current
          echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
        shell: bash

      - name: create symbolic link without extension 
        id: push_to_production
        run: |


            git checkout production
            git checkout ${BRANCH} -- data_descriptors

            find . -type f -name "*.json" -exec sh -c 'ln -s "$0" "${0%.json}"' {} \;

            git add -A;
            git commit -m "production push";
            git push --force origin production;

            # mv data_descriptors/*/ ./
            # rm -rf data_descriptors
            
            # cd data_descriptors;
            # find . -type f -name "*.json" -exec sh -c 'ln -s "$0" "${0%.json}"' {} \;
            # git add .;
            # git commit -m "production push";
            # git push --force origin production;

      
