name: Source_ID_dispatch

on:
  repository_dispatch:
    types:
      - source_id

jobs:
  process-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Payload
        run: |
          echo "Received Payload:"
          echo "Key: ${{ github.event.client_payload.key }}"
          echo "AnotherKey: ${{ github.event.client_payload }}" >> $GITHUB_STEP_SUMMARY
          echo "AnotherKey: ${{ github.event.client_payload.anotherKey }}" >> $GITHUB_STEP_SUMMARY

      - name: Set up Credentials
        run: |
          # Set the GitHub username
          github_username="jacobp100"
          
          # Set Git user config locally
          git config --global user.email "${github_username}@users.noreply.github.com"
          git config --global user.name "${github_username}"

      - name: Create and push new branch
        run: |
          # Set the branch names
          
          new_branch="feature-branch"
          
          # Create a new branch
          git checkout -b $new_branch
          
          # Create a new file (replace with actual file creation logic)
          echo "Hello, this is a new file." > new-file.txt

          # Commit and push the changes
          git add new-file.txt
          git commit -m "Add new file"
          git push origin $new_branch
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "A test commit "
            title: "Do not merge!"
            body: "Your Pull Request Description"
            branch: feature-branch
            base: main
