name: Source_ID_dispatch

on:
  repository_dispatch:
    types:
      - source_id

jobs:
  process-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Payload
        run: |
          echo "Received Payload:"
          echo "Key: ${{ github.event.client_payload.key }}"
          echo "AnotherKey: ${{ github.event.client_payload.anotherKey }}" >> $GITHUB_STEP_SUMMARY

      - name: Create and push new branch
        run: |
          # Set the branch names
          base_branch="main"
          new_branch="feature-branch"
          
          # Set the GitHub username
          github_username="wolfiex"
          
          # Set Git user config locally
          git config user.email "${github_username}@users.noreply.github.com"
          git config user.name "${github_username}"

          # Create a new branch
          git checkout -b $new_branch
          
          # Create a new file (replace with actual file creation logic)
          echo "Hello, this is a new file." > new-file.txt

          # Commit and push the changes
          git add new-file.txt
          git commit -m "Add new file"
          git push origin $new_branch

      - name: Create Pull Request to Main
        run: |
          # Set the branch names (do this globally)
          base_branch="main"
          feature_branch="feature-branch"

          # Set the GitHub username
          github_username="wolfiex"
          
          # Set Git user config locally
          git config user.email "${github_username}@users.noreply.github.com"
          git config user.name "${github_username}"

          # Set the title and body of the pull request
          pr_title="Automated PR to Main"
          pr_body="This pull request was automatically created by a GitHub Actions workflow."

          # Set the GITHUB_TOKEN environment variable for authentication
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Create the pull request using GitHub REST API
          response=$( \
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"title":"'$pr_title'","body":"'$pr_body'","head":"'$feature_branch'","base":"'$base_branch'"}' \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls" \
          )

          # Extract the pull request URL from the API response
          pr_url=$(echo "$response" | jq -r .html_url)

          echo "Pull Request created successfully: $pr_url"
