name: Source_ID_dispatch

on:
  repository_dispatch:
    types:
      - source_id

jobs:
  process-payload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Payload
        run: |
          echo "Received Payload:"
          echo "Key: ${{ github.event.client_payload.key }}"
          echo "AnotherKey: ${{ github.event.client_payload }}" >> $GITHUB_STEP_SUMMARY
          echo "AnotherKey: ${{ github.event.client_payload.anotherKey }}" >> $GITHUB_STEP_SUMMARY

      - name: Set up Credentials
        run: |
          # Set the GitHub username
          github_username="jacobp100"
          
          # Set Git user config locally
          git config --global user.email "${github_username}@users.noreply.github.com"
          git config --global user.name "${github_username}"

      - name: Create and push new branch
        run: |

          github_username="jacobp100"
          
          # Set Git user config locally
          git config --global user.email "${github_username}@users.noreply.github.com"
          git config --global user.name "${github_username}"
          # Set the branch names
          new_branch="feature-branch"
          
          # Create a new branch
          git checkout -b $new_branch
          
          # Create a new file (replace with actual file creation logic)
          echo "Hello, this is a new file." > new-file.txt

          # Commit and push the changes
          git add new-file.txt
          git commit -m "Add new file"
          git push origin $new_branch
  
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #       token: ${{ secrets.GITHUB_TOKEN }}
      #       commit-message: "A test commit "
      #       title: "Do not merge!"
      #       body: "Your Pull Request Description"
      #       branch: feature-branch
      #       base: main

      # - name: Update Pull Request Description on Push
      #   # You may pin to the exact commit or the version.
      #   # uses: kt3k/update-pr-description@46409be4b4fb57502e7a0c40a317d79b21a548dd
      #   uses: kt3k/update-pr-description@v2.1.1
      #   with:
      #     # The GITHUB_TOKEN secret
      #     github_token:  ${{ secrets.GITHUB_TOKEN }}
      #     # The title of the PR
      #     pr_title: 'test'
      #     # The body of the PR
      #     pr_body: 'another test'
      #     # Base branch of the PR. Default is master.
      #     destination_branch: main
      #     # Raise an exception and mark the action as failed in case of error
      #     fail_on_error: # optional, default is true

      - name: Create Pull Request
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITHUB_USERNAME: wolfiex
        run: |
            base_branch="main"
            feature_branch="feature-branch"

            git config --global user.email "${GITHUB_USERNAME}@users.noreply.github.com"
            git config --global user.name "${GITHUB_USERNAME}"

            gh pr create --base $base_branch --head $feature_branch --title "Automated PR to Main" --body "This pull request was automatically created by a GitHub Actions workflow." --reviewer $GITHUB_USERNAME
      