name: Untrack File on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_run:
     workflows: ["File Versioning"]
     types:
     - completed
     
env:
  API_KEY: ${{ secrets.API_KEY }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  
jobs:
  untrack-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Untrack file on pull request
      run: |
        git config --global user.email "actions@wcrp-cmip.org"
        git config --global user.name "CMIP-IPO GitHub Action"
        
        git rm 'CVs/*.json' 
        git commit -m "Untrack file for pull request" --allow-empty
        git push origin HEAD:${{ github.event.before }}-untrack-file
