'''
#!/bin/bash

# Set the path to your repository
repo_path="/path/to/your/repository"

# Set the key to search for
search_key="version_metadata"

# Use find and grep to search for files containing the key
files_with_version_metadata=$(find "$repo_path" -type f -exec grep -l "$search_key" {} +)

# Print the list of files
echo "Files with $search_key:"
echo "$files_with_version_metadata"

'''


import argparse

parser = argparse.ArgumentParser(description='Calculate and validate checksums for CV files and update the version metadata.')
parser.add_argument('files', nargs='*', help='List of files to process')
# parser.add_argument('-a', '--all', action='store_true', help='Process all files in the current directory')

args = parser.parse_args()

# if args.all:
#     # Process all files in the current directory
#     files = [filename for filename in os.listdir('.') if os.path.isfile(filename)]
# else:


metadata = '''
    {
        "version_metadata": {
            "file_updated": "{file_updated}",
            "CVs": {
                "updated": "{cvs_updated}",
                "tag": "{cvs_tag}",
                "commit": "{cvs_commit}"
            },
            "MIP tables": {
                "updated": "{mip_tables_updated}",
                "tag": "{mip_tables_tag}",
                "commit": "{mip_tables_commit}"
            },
            "autogenerated": "{autogenerated}"
        }
    }
'''
{
    "Header": {
        "latest change": {
            "author": "Daniel Ellis <daniel.ellis@ext.esa.int>",
            "institution_id": "CMIP-IPO"
        },
        "specs_doc": "v6.3.0 (link TBC)",
        "CMIP6Plus_CVs": {
            "CV_collection_modified": "2023-11-03",
            "CV_collection_version": "6.5.0",
            "previous_commit": "6.5.0"
        },
        "MIP_Tables": {
            "tag": "v6.5.0.0",
            "commit": "490b9b82ee74b63c8adaade114763f88f89feb2e",
            "Repository URL": "https://github.com/PCMDI/mip-cmor-tables.git",
            "license": "LICENSE-CC-BY"
        },
        "CMOR": "3.7.3",
        "CVTool": "0.2.0"
    },


  "Header": {
    "CV_collection_modified": "2022-09-05",
    "CV_collection_version": "6.3.0.0",
    "author": "Matt Mizielinski <matthew.mizielinski@metoffice.gov.uk>",
    "checksum": "md5: f26f4d1c70643d47eced87583272f081",
    "institution_id": "MOHC",
    "previous_commit": "To be added",
    "specs_doc": "v6.3.0 (link TBC)"
  },

for filename in args.files:

